DESIGN_NAME: rd_5_32

VERILOG_FILES:
  - dir::rd_5_32.sv
  - dir::rd_2_4.sv
  - dir::rd_3_8.sv

# CLOCK_PORT: clk
# CLOCK_PERIOD: 25

# PDK / stdcell libraryâ€“specific settings
pdk::gf180mcuD:
  scl::gf180mcu_fd_sc_mcu9t5v0:

    # Use only this timing corner
    DEFAULT_CORNER: tt_025C_3v30
    STA_CORNERS: [tt_025C_3v30]

    # Point that corner to a specific .lib
    LIB:
      tt_025C_3v30:
        - "pdk_dir::libs.ref/gf180mcu_fd_sc_mcu9t5v0/lib/gf180mcu_fd_sc_mcu9t5v0__tt_025C_3v30.lib"
        # or, if you have a local custom lib:
        # - "/absolute/path/to/your_custom_tt_025C_5v00.lib"